[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x282c34'
foreground = '0xdcdfe4'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1c2023'
cursor = '0xc7ccd1'

# Normal colors
[colors.normal]
black = '0x282c34'
red = '0xe06c75'
green = '0x98c379'
yellow = '0xe5c07b'
blue = '0x61afef'
magenta = '0xc678dd'
cyan = '0x56b6c2'
white = '0xdcdfe4'

# Bright colors
[colors.bright]
black = '0x282c34'
red = '0xe06c75'
green = '0x98c379'
yellow = '0xe5c07b'
blue = '0x61afef'
magenta = '0xc678dd'
cyan = '0x56b6c2'
white = '0xdcdfe4'
